<?php

/**
 * Remove the required attributes from divs that don't support them (w3c validity fix)
 * @param $variables
 */
function a11yformsfix_preprocess_form_element(&$variables) {
    $remove_from_types = array('webform_radios_other', 'webform_checkboxes_other');
    if (in_array($variables['element']['#type'], $remove_from_types)) {
        unset($variables['attributes']['required']);
        unset($variables['attributes']['aria-required']);

        $variables['label_display'] = 'hidden';
    }
}

/**
 * Remove the required attributes from divs that don't support them (w3c validity fix)
 * @param $variables
 */
function a11yformsfix_preprocess_fieldset(&$variables) {
    $remove_from_types = array('radios', 'checkboxes', 'webform_radios_other', 'webform_checkboxes_other');
    if (in_array($variables['element']['#type'], $remove_from_types)) {
        //var_dump($variables);exit();
        unset($variables['attributes']['required']);
        unset($variables['attributes']['aria-required']);
    }
}

/**
 * Override these elements with our own processor to add the correct `required` attributes
 * 
 * @param $info
 */
function a11yformsfix_element_info_alter(&$info) {
    $info['radios']['#process'][0][0] = 'Drupal\a11yformsfix\Element\Radios';

    $info['webform_radios_other']['#process'][] = array(
        'Drupal\a11yformsfix\Element\Radios',
        'preRenderCompositeFormElement'
    );
}
